version: '2'
services:
  db:
    restart: always
    image: postgres:12
    volumes:
      - fider-test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: s0m3g00dp4ssw0rd
  app:
    restart: always
    image: fider
    ports:
      - "9999:3000"
    environment:
      ###
      # REQUIRED
      #
      # All these settings are required
      ###

      HOST_DOMAIN: localhost

      # Use production for best performance
      # Use development for verbose logs
      GO_ENV: development

      # Connection string to the PostgreSQL database.
      # This example uses the Docker service defined above
      DATABASE_URL: postgres://fider:s0m3g00dp4ssw0rd@db:5432/fider?sslmode=disable

      # CHANGE THIS! You can generate a strong secret at https://randomkeygen.com/
      JWT_SECRET: ...

      # From which account e-mails will be sent (required)
      EMAIL_NOREPLY: noreply@example.com

      ###
      # EMAIL
      #
      # Either EMAIL_MAILGUN_* or EMAIL_SMTP_* is required
      ###

      EMAIL_SMTP_HOST: smtp.example.com
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USERNAME: noreply@example.com
      EMAIL_SMTP_PASSWORD: password

      DISCORD_WEBHOOK: https://discord.com/api/webhooks/...
    depends_on:
      - db
volumes:
  fider-test:
